version: '3'
services:
  database:
    image: postgres:10.5-alpine
    ports:
      - 5432:5432
    volumes:
      - databasedata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    image: cadastropessoa-back:latest
    ports:
      - 8082:8082
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
volumes:
  databasedata: